[package]
name="kitt-domain"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true

[dependencies]
serde.workspace=true
thiserror.workspace=true
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory.git", rev = "be6b254fd48b7c7a7a9bbe9f5b98fb579fbd5279" }
