[package]
name="kitt-domain"
version.workspace=true
edition.workspace=true
rust-version.workspace=true
license.workspace=true

[dependencies]
serde.workspace=true
thiserror.workspace=true
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "e65330ab60cf986dc9eb10fea0509e4f8b10cea3" }
