[package]
name = "kitt-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-domain = { path = "../kitt-domain" }
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "37e677696a9f1ea0e5bbcffd911991971e83a9aa" }
kitt-memory-sqlite = { git = "https://github.com/rfdetoni/kitt-memory", rev = "37e677696a9f1ea0e5bbcffd911991971e83a9aa" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
