[package]
name = "kitt-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-domain = { path = "../kitt-domain" }
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "48384a5e8bb592226cc55abc24c2011fcbdf9dfe" }
kitt-memory-sqlite = { git = "https://github.com/rfdetoni/kitt-memory", rev = "48384a5e8bb592226cc55abc24c2011fcbdf9dfe" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
