[package]
name = "kitt-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-domain = { path = "../kitt-domain" }
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "e65330ab60cf986dc9eb10fea0509e4f8b10cea3" }
kitt-memory-sqlite = { git = "https://github.com/rfdetoni/kitt-memory", rev = "e65330ab60cf986dc9eb10fea0509e4f8b10cea3" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
