[package]
name = "kitt-hud"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[lib]
name = "kitt_hud_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "90882e9a44001e96fa84bc30e235d86687e08825" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
