[package]
name = "kitt-hud"
version = "0.1.3"
edition = "2024"
rust-version = "1.85"

[lib]
name = "kitt_hud_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "937b96863d12b10222f3ee7b92a939ee198c654c" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
