[package]
name = "kitt-hud"
version = "0.1.4"
edition = "2024"
rust-version = "1.85"

[lib]
name = "kitt_hud_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "de66291bc05f9b83a6a2cfaf5b179428d4e7d79f" }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
