[package]
name = "kittd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-domain = { path = "../../crates/kitt-domain" }
kitt-application = { path = "../../crates/kitt-application" }
kitt-infrastructure = { path = "../../crates/kitt-infrastructure" }
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "c4ae476521e812ec1497a442cce6b276a26d9f80" }
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "f3031588bc68e47db1f3ffa61f280c7ad8488c52" }
kitt-memory-sqlite = { git = "https://github.com/rfdetoni/kitt-memory", rev = "f3031588bc68e47db1f3ffa61f280c7ad8488c52" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dirs.workspace = true
base64.workspace = true
url.workspace = true
cpal.workspace = true
hound.workspace = true
rustpotter.workspace = true
reqwest.workspace = true
