[package]
name = "kittd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-domain = { path = "../../crates/kitt-domain" }
kitt-application = { path = "../../crates/kitt-application" }
kitt-infrastructure = { path = "../../crates/kitt-infrastructure" }
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "90882e9a44001e96fa84bc30e235d86687e08825" }
kitt-memory-core = { git = "https://github.com/rfdetoni/kitt-memory", rev = "53d4d3325992ddd3505a1ac6fe59357dcf901a97" }
kitt-memory-sqlite = { git = "https://github.com/rfdetoni/kitt-memory", rev = "53d4d3325992ddd3505a1ac6fe59357dcf901a97" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
dirs.workspace = true
base64.workspace = true
url.workspace = true
cpal.workspace = true
hound.workspace = true
rustpotter.workspace = true
