[package]
name = "kittctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "de66291bc05f9b83a6a2cfaf5b179428d4e7d79f" }
serde_json.workspace = true
dirs.workspace = true
