[package]
name = "kittctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kitt-protocol = { git = "https://github.com/rfdetoni/kitt-protocol", rev = "97e1cad8dfc6d3a74fe2332530dc01a25e476516" }
serde_json.workspace = true
dirs.workspace = true
